image: cerw/docker-laravel
services:
  - mysql:5.7

cache:
  untracked: true
  key: "secca-laravel"
  paths:
    - node_modules
    - vendor
    - /root/.composer
    - /root/.npm

variables:
  MYSQL_DATABASE: secca_testing
  MYSQL_ROOT_PASSWORD: secret

stages:
  - build
  - tests
  - deploy

build:
  stage: build
  script:
    - mkdir -vp `pwd`/vendor
    - mkdir -vp `pwd`/node_modules
    - bash .gitlab-ci.sh

features:
  stage: tests
  before_script:
      - cp .env.gitlab .env
  script:
    - php vendor/bin/phpunit --coverage-text --colors=never ./tests/Feature

browser:
  stage: tests
  before_script:
    - cp .env.gitlab .env
  script:
    - /usr/bin/supervisord
    - sleep 3
    - php vendor/bin/phpunit --coverage-text --colors=never ./tests/Browser
  artifacts:
      name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
      paths:
      - tests/Browser/screenshots/
      expire_in: 4 weeks
      when: always

deploy_staging:
  stage: deploy
  script:
    - curl -X POST https://deploy.nano.rocks/XXX-d "reason=$CI_COMMIT_REF_SLUG"
  environment:
    name: staging
    url: https://secca.nano.rocks
  only:
  - master

deploy_production:
  stage: deploy
  script:
    - curl -X POST https://deploy.nano.rocks/XXX -d "reason=$CI_COMMIT_REF_SLUG"
  environment:
    name: production
    url: http://app.secca.org.au
  only:
  - production
